# Generated by Django 4.2.1 on 2023-05-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('model_year', models.CharField(max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autoservice.clients')),
            ],
        ),
    ]
