# Generated by Django 4.2.1 on 2023-05-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_typeservice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='model_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
